### ISSUE TITLE
搜索结果中是否可以添加原图链接

### ISSUE THREAD

**Issue by mashirozx** [cheer-fun/Pixiv-Illustration-Collection-Backend#18]
有时候希望关注一下插画作者、或者收藏插画，如果可以给个在pixiv上查看原图页面的链接就好了。

PS. 我这边加载大图速度比较慢，是否有可能使用自定义镜像，比如 <https://pixiv.cat/reverseproxy.html> 这样的。

**Comment by OysterQAQ** [comment]
有原图链接的,自定义镜像暂时没有这个计划
