### ISSUE TITLE
关于xRestrict参数无法使用的问题

### ISSUE THREAD

**Issue by CafuuChino** [cheer-fun/Pixiv-Illustration-Collection-Backend#22]
出现了在GET请求中将xRestrict参数设为1时返回空白的问题

**Comment by OysterQAQ** [comment]
已修复

**Comment by Pzzzzz5142** [comment]
（我也遇到了，，，

**Comment by OysterQAQ** [comment]
> （我也遇到了，，，

xRestrict为1都是限制级别非常高的高危图片，在搜索中是屏蔽的

**Comment by Pzzzzz5142** [comment]
> > （我也遇到了，，，
> 
> xRestrict为1都是限制级别非常高的高危图片，在搜索中是屏蔽的

（那我想看能设置出来吗？

毕竟正常搜索maxSanityLevel设高点也有标签为xRestrict=1的图

**Comment by OysterQAQ** [comment]
xRestrict=1的时候sanity基本是>=6的 已经属于r18了 所以不提供设置

**Comment by Pzzzzz5142** [comment]
ok
